# Generated by Django 4.1 on 2022-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="rating_post", field=models.FloatField(default=0),
        ),
    ]
