# Generated by Django 4.1 on 2022-08-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewsApp", "0002_alter_post_rating_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user_commemt", new_name="user_comment",
        ),
    ]
